name: Nexus.ai

services:
  nexus-api:
    build: backend/
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./backend/app:/code/app
    depends_on:
      - nexus-db
    networks:
      - nexus-network
    env_file:
      - .env
    environment:
      - DEBUG=true # Change to false if you're not debugging


  nexus-db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - nexus-network

  nexus-web:
    build: frontend/nexus-web/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/nexus-web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - nexus-api
    networks:
      - nexus-network

volumes:
  postgres_data:

networks:
  nexus-network:
    driver: bridge